remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Welcom to VeroX inc. website]
description: [There will be located all my project and custom roms and ported roms]
